version: "3.9"
services:
  postgres:
    container_name: docker_pg
    image: postgres:16
    environment:
      POSTGRES_DB: "docker_pg"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerty007"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"