version: "3.9"
services:
  postgres:
    container_name: docker_pg
    image: postgres:16
    environment:
      POSTGRES_DB: "docker_pg"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerty007"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"